networks:
  loki:
  influxdb:

services:

  influxdb:
    container_name: influxdb2
    image: influxdb:2.7.1
    env_file: .env
    ports:
      - "8086:8086"
    restart: always
    networks:
      - influxdb
    volumes:
      - ./influxdb_data:/var/lib/influxdb2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/health"]
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 10s
      
  loki:
    container_name: loki
    image: grafana/loki:2.9.4
    ports:
      - "3100:3100"
    restart: always
    volumes:
      - ./loki/loki-config.yaml:/etc/loki/config.yaml
      - ./loki_data:/loki
    command: -config.file=/etc/loki/config.yaml
    networks:
      - loki
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3100/ready"]
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 10s

  grafana:
    container_name: grafana
    image: grafana/grafana:10.0.3
    user: root
    depends_on:
      influxdb:
        condition: service_healthy
      loki:
        condition: service_healthy
    env_file: .env
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - ./grafana/provider:/etc/grafana/provisioning/dashboards
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/data:/var/lib/grafana
    networks:
      - loki
      - influxdb